# Generated by Django 5.2.6 on 2025-10-23 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='additional',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
